feat: free-threaded Python (3.13.0+) support
jpy-consortium/jpy pull request #165
Opened 2024-09-17 21:45 UTC by jmao-denver

Fixes #163

2024-10-25 17:12 UTC, devinrsmith commented on src/main/c/jpy_jobj.c
> +            JPy_XDECREF(callable);
This is maybe a question not directly related to this new feature; I don't think we use JPy_Type_Translations, but in the case where we _do_, should obj be DECREFd?

2024-10-25 17:12 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +static void acquire_lock(ReentrantLock* self) {
Is this a pattern that you found suggested by C python, or elsewhere?

2024-10-25 17:12 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +static void acquire_lock(ReentrantLock* self) {
`self` is an "interesting" choice; do we think `lock` would be better?

2024-10-25 17:12 UTC, devinrsmith commented on src/main/java/org/jpy/PyObjectReferences.java
> +            if (!e.getMessage().contains("PyLib not initialized")) {
`e.getMessage()` may be null.

2024-10-25 17:12 UTC, devinrsmith commented on src/main/java/org/jpy/PyObject.java
> -            if (CLEANUP_ON_INIT && PyLib.hasGil()) {
I think the hasGil check is important... esp on older versions?

2024-10-25 17:12 UTC, devinrsmith commented on jpyutil.py
I did not review this file yet, but I will next pass.

2024-10-25 18:25 UTC, cpwright commented on src/main/c/jpy_jtype.c
> +#define ACQUIRE_GET_TYPE_LOCK() acquire_lock(&get_type_rlock)
TODO: Charles make sure we have no inversions.

2024-10-25 18:25 UTC, cpwright commented on src/main/c/jpy_jtype.c
> +    if (PyDict_GetItemStringRef(JPy_Type_Callbacks, declaringClass->javaName, &callable) != 1) {
The GetItemStringRef is new in 3.13; but doesn't seem entirely related to the GIL-less changes.  It looks like a more robust API, should we use it always?

2024-10-25 18:25 UTC, cpwright commented on src/main/java/org/jpy/PyObject.java
>                  REFERENCES.cleanupOnlyUseFromGIL(); // only performs *one* cleanup
If we are no longer using the GIL, then we should rename this function and instead have comments on why it is correct.  If we are on 3.12 mode why are we still correct?

2024-10-25 18:25 UTC, chipkent commented on src/main/c/jpy_jtype.c
> +    callable = PyDict_GetItemString(JPy_Type_Callbacks, declaringClass->javaName); // borrowed reference
```suggestion
    // borrowed ref, no need to replace with PyDict_GetItemStringRef because it is protected by the lock
    callable = PyDict_GetItemString(JPy_Type_Callbacks, declaringClass->javaName); 
```

2024-10-25 18:25 UTC, chipkent commented on src/main/c/jpy_jtype.c
> +    // borrowed ref, no need to replace with PyDict_GetItemRef because it protected by the lock
```suggestion
    // borrowed ref, no need to replace with PyDict_GetItemRef because it is protected by the lock
```

2024-10-25 19:23 UTC, cpwright commented on .github/workflows/build.yml
> +          - { machine: 'ubuntu-20.04', python: '3.13t', arch: 'aarch64', cmd: '.github/env/Linux/bdist-wheel.sh' }
20.04 goes EOL 4/23/2025.  We may consider bumping to at least 22.04 which.

2024-10-25 19:42 UTC, jmao-denver commented on .github/workflows/build.yml
> +      - uses: astral-sh/setup-uv@v3
I agree with, it really depends on when GH actions add the free-threaded Python support.

2024-10-25 19:47 UTC, jmao-denver commented on .github/workflows/build.yml
> -      - run: pip install setuptools
Not relevant, just clean up a bit because the `cmd` script already makes sure all the needed packages are installed.

2024-10-25 19:56 UTC, jmao-denver commented on .github/workflows/build.yml
> +          - { machine: 'macos-latest', python: '3.13t', arch: 'arm64', cmd: '.github/env/macOS/bdist-wheel.sh' }
No universal2 wheel for FT build yet.

2024-10-25 21:21 UTC, cpwright commented on src/main/c/jpy_jtype.c
> +#define ACQUIRE_RESOLVE_TYPE_LOCK() acquire_lock(&resolve_type_rlock)
I think you need to add comments describing what these locks protect.

I think that you might be missing a case where the type dictionary is accessed in JType_AddField which has the resolve lock, but not the type lock.

Combining these two locks might be safer, as I think inversions could be possible as well.

2024-10-29 18:44 UTC, jmao-denver commented on .github/workflows/build.yml
> +          - { machine: 'ubuntu-20.04', python: '3.13t', arch: 'aarch64', cmd: '.github/env/Linux/bdist-wheel.sh' }
@devinrsmith is almost certainly changing to 22.04 will make the wheels not installation due to some incompatiblity in the glibc etc. Will file a follow-up ticket.

2024-10-29 18:59 UTC, devinrsmith commented on .github/workflows/build.yml
> +          - { machine: 'ubuntu-20.04', python: '3.13t', arch: 'aarch64', cmd: '.github/env/Linux/bdist-wheel.sh' }
We are currently targeting manylinux_2_17, which makes it compatible with GLIBC version 2.17+; afaict, the building of these artifacts needs to happen on a system w/ GLIBC version 2.17, and updating to 22.04 or later breaks this. We should have a ticket about GLIBC version support, and when we will move on past 2.17.

2024-10-29 21:55 UTC, devinrsmith commented on .github/workflows/build.yml
> +          - { machine: 'ubuntu-20.04', python: '3.13t', arch: 'aarch64', cmd: '.github/env/Linux/bdist-wheel.sh' }
https://github.com/pypa/cibuildwheel/issues/1772 has relevant upstream comments about the topic.

2024-10-30 15:45 UTC, jmao-denver commented on .github/workflows/build.yml
> +        uses: pypa/cibuildwheel@v2.21.3
This still uses emulation but the nice thing about CBW under aarch64 simulation is that it can build both amd64 and aarch64 wheels.

2024-10-30 15:54 UTC, jmao-denver commented on .github/workflows/build.yml
> +          - { machine: 'windows-2022', python: '3.13t', arch: 'amd64', cmd: '.\.github\env\Windows\bdist-wheel.ps1' }
Yes, I am watching https://github.com/actions/setup-python/issues/771

2024-10-30 17:31 UTC, jmao-denver commented on src/main/c/jpy_jobj.c
> +            JPy_XDECREF(callable);
I think you are right.

2024-10-30 17:33 UTC, jmao-denver commented on src/main/c/jpy_jtype.c
> +static void acquire_lock(ReentrantLock* self) {
C Python doesn't offer an reentrant lock primitive. This is a pattern I found somewhere else.

2024-10-30 20:51 UTC, jmao-denver commented on src/test/python/jpy_mt_eval_exec_test.py
> +NUM_THREADS = 20
The standard GH hosted runner comes with 4 or fewer cores, https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories. 20 is really just a gut-feeling threshold but should be big enough to create contention among threads without incurring too much context switch. If we were to upgrade to larger runners (need to pay), we most likely need to make it a lot bigger to detect potential race conditions.

2024-10-31 19:13 UTC, jmao-denver commented on src/main/java/org/jpy/PyObject.java
>                  REFERENCES.cleanupOnlyUseFromGIL(); // only performs *one* cleanup
This change is made to fix a bug based on the two following observations:
1.  Because we now release the GIL whenever we cross into Java from Python (by @niloc132), the PyLib.hasGIL()  test will always fail in Python GIL enabled mode,  which results in that the cleanup method can never get called. (BTW, in the GIL disabled mode, PyLib.hasGIL() returns true).
2. As part of the same enhancement change by @niloc132, he made sure that the cleanup is done under GIL.
```
    private int cleanupOnlyUseFromGIL(long[] buffer) {
        return PyLib.ensureGil(() -> {
            int index = 0;
            while (index < buffer.length) {
                final Reference<? extends PyObject> reference = referenceQueue.poll();
                if (reference == null) {
   ...
```

2024-10-31 19:22 UTC, niloc132 commented on src/main/java/org/jpy/PyObject.java
>                  REFERENCES.cleanupOnlyUseFromGIL(); // only performs *one* cleanup
@jmao-denver is right, there are several layers of questionable here, and the latest round here is my fault. 
 * latest stable release: hasGil is always false here, so this block never executes
 * prior to the "release gil while in Java" change: hasGil is always _true_, so this _always_ runs.
 
Why did it even test to begin with? Why does it clean up all other object any time any PyObject is about to be passed in to Java (instead of just once either just before or just after calling Java)? Couldn't say. I think removing the check is correct (either just before the ft patch, or as part of it), and we should reevaluate what is even happening here separately.

Agreed on renaming cleanupOnlyUseFromGIL.

2024-10-31 20:22 UTC, jmao-denver commented on src/test/python/jpy_mt_eval_exec_test.py
> +        self.fixture.script("baz = baz + 1; self.assertGreater(baz, 15)", NUM_THREADS)
I think this is sufficient to ensure the multithreaded execution of a piece of code behaves the same when GIL is disabled and when it is enabled. Additional, more complex scripts in the tests only amount to testing that Python FT build is thread-safe just as the regular build.

2024-11-02 16:44 UTC, jmao-denver commented on src/main/c/jpy_module.c
> +    return JObj_FromType(jenv, targetTypeParsed, objectRef);
To fix a bug that failed to initialize `JPy_JArray` properly, which leads to a memory issue in the FT build, possibly due to some specific change in the Python C API (`PyType_GenericAlloc`) or the underlying memory management module used that no longer implicitly zero initialize the allocated memory.

I have tried to reproduce the problem with the GIL enabled build of <= 3.13 versions and confirmed that `JPy_JArray` has always be 'implicitly' zero initialized.

2024-11-04 16:41 UTC, jmao-denver commented on src/main/c/jpy_module.c
> +        JPy_DECREF(targetTypeParsed);
This is a bit anti-pattern. But with the insider knowledge that the type is stored in a dictionary and guarded by the locks, it is safe to use. Will change to avoid the confusing.

2024-11-04 21:22 UTC, chipkent commented on src/main/c/jpy_module.c
> +        JPy_DECREF(targetTypeParsed);
If it requires insider knowledge, it should have a comment at minimum.

2024-11-05 17:31 UTC, devinrsmith commented on .github/workflows/build.yml
> +          - { machine: 'macos-latest', python: '3.13t', java: '11', arch: 'arm64', cmd: '.github/env/macOS/bdist-wheel.sh' }
I'm not a fan of using "latest"; let's pin this to `macos-14` for now, until we have reason to change it.

2024-11-05 17:31 UTC, devinrsmith commented on .github/workflows/check.yml
> +            echo PATH=$PATH >> $GITHUB_ENV
This looks like it is still using GITHUB_ENV?

2024-11-05 17:31 UTC, devinrsmith commented on src/main/c/jni/org_jpy_PyLib.c
> +#ifdef Py_GIL_DISABLED
I think the preference is to still use the critical section macros for 3.13+, even if the GIL is enabled. If the GIL is enabled, the macros simply expand to `{` / `}`.

If we want, we can define our own macro, `JPy_BEGIN_CRITICAL_SECTION` / `JPy_END_CRITICAL_SECTION` if we find we are need to use the pattern a lot.

2024-11-05 17:31 UTC, devinrsmith commented on jpyutil.py
> +        sys.gettotalrefcount()
I think

```python
import sysconfig

sysconfig.get_config_var('Py_DEBUG')
```

would be better?

It looks like technically debug ref counting is more specific than plain debug.

https://pythonextensionpatterns.readthedocs.io/en/latest/debugging/debug_python.html#the-debug-builds
https://pythonextensionpatterns.readthedocs.io/en/latest/debugging/debug_python.html#identifying-the-python-build-configuration-from-the-runtime

2024-11-05 17:50 UTC, devinrsmith commented on src/test/java/org/jpy/fixtures/MultiThreadedEvalTestFixture.java
> +                throw new RuntimeException(e);
If we are not going to throw an exception, probably best to explicitly return as well.

2024-11-05 18:14 UTC, devinrsmith commented on src/main/java/org/jpy/PyObject.java
>                  REFERENCES.cleanupOnlyUseFromGIL(); // only performs *one* cleanup
This was an oversight on my part during the "drop GIL" review.

I made the argument during the review that we might prefer to have some way to keep the GIL during "quick" java calls, or in other cases where we explicitly want to keep the GIL. I might argue that our call from `JType_CreateJavaPyObject` into the constructor of `PyObject` should keep the GIL.

The reason we need this to only be called into the context of the GIL (historically) is because we need the GIL when calling `PyLib.decRef`; I'm assuming in the case of free-threaded (/GIL-less) builds, Py_DECREF is thread safe. And it's not only that Py_DECREF that needs to be thread-safe, the arbitrary python deallocation code that can be executed as part of a decRef to 0 needs to be thread-safe.

In the context of free-threaded / GIL-less builds, maybe the functions need to be renamed to be something like `PyLib.isThreadSafe` / `PyLib.ensureThreadSafe`, or something like that.

2024-11-06 14:48 UTC, chipkent approved these changes

2024-11-06 15:43 UTC, devinrsmith requested changes

2024-11-06 15:43 UTC, devinrsmith commented on jpyutil.py
> +    debug_build = sysconfig.get_config_var('Py_DEBUG')
This is not correct in the context of how you are using it. It needs to be checked if it's set to "1"; at least in my builds, it's explicitly set to "0":

```
python3.8 -m sysconfig | grep Py_DEBUG    
        Py_DEBUG = "0"
```

After some more reading, I actually think that `sys.abiflags` is the more appropriate place to check, since it's _specifically_ mentioned as being set for debug builds, https://docs.python.org/3.10/using/configure.html#python-debug-build:

> Effects of a debug build:
> * Add `d` to [sys.abiflags](https://docs.python.org/3.10/library/sys.html#sys.abiflags).

2024-11-06 15:43 UTC, devinrsmith commented on src/main/java/org/jpy/PyObject.java
> +            if (CLEANUP_ON_INIT) {
Although originally unintentional (I think), this _is_ a change in behavior vs the current release. I might suggest Colin or I follow up with a PR, unless this is newly tested in this PR?

2024-11-06 15:47 UTC, devinrsmith commented on jpyutil.py
> +    debug_build = sysconfig.get_config_var('Py_DEBUG')
Sorry for my flip-flopping; it actually looks like `.get_config_var` is correct, since it seems to return an int when used like this. That said, maybe we should still prefer `sys.abiflags` since it's more explicitly documented?

2024-11-07 03:05 UTC, jmao-denver commented on jpyutil.py
> +    debug_build = sysconfig.get_config_var('Py_DEBUG')
<img width="970" alt="image" src="https://github.com/user-attachments/assets/889aad8b-ddd0-4408-bddd-cc1e7c621866">

`Py_DEBUG` is also explicitly mentioned there. Also a quick ChatGPT inquiry yields this;

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/23eeeffe-1fb8-4877-ae08-886031792b08">

I think we should be comfortable with using  the value of `Py_DEBUG` in `sysconfig`

2024-11-07 03:24 UTC, jmao-denver commented on src/main/java/org/jpy/PyObject.java
> +            if (CLEANUP_ON_INIT) {
It isn't explicitly tested. But the code path does get executed implicitly in `jpy_typeconv_test_pyobj.py`.

2024-11-07 03:38 UTC, devinrsmith commented on jpyutil.py
> +    debug_build = sysconfig.get_config_var('Py_DEBUG')
I'm not confident that `Py_DEBUG and Py_REF_DEBUG macros` are guaranteed to be equivalent to "config vars"; that said, it looks like `sys.abiflags` doesn't work on Windows, so I guess get_config_var is the best way for now.

It looks like there was a patch many years ago to add an official way to look up if it was built with debug, but it was not merged. https://github.com/python/cpython/issues/69443

2024-11-07 03:41 UTC, devinrsmith approved these changes

2024-11-07 04:12 UTC, merged