Use valueOf() to box primitive values instead of creating new objects every time
jpy-consortium/jpy pull request #88
Opened 2022-09-23 19:15 UTC by rbasralian

2022-09-23 23:38 UTC, devinrsmith requested changes
I like it. Few small things.

2022-09-23 23:38 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +#define JType_CallStaticObjectMethodPrimitiveArgAndReturn(TARGET_TYPE, STATIC_METHOD_ID, VALUE, JOBJECT_PTR) \
I think we want to give a better indication that this is a macro - I think we use all caps elsewhere.

2022-09-23 23:38 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +    Py_END_ALLOW_THREADS; \
It's not clear to me that we should / want to drop and then re-acquire the GIL (even thought the previous code to this _was_). In the other cases of CallStaticObjectMethod (and NewObject, etc) we are usually calling _arbitrary_ pieces of code - at least in the context of this patch, we are only calling short valueOf methods.

@niloc132 @jmao-denver may have perspective as well.

2022-09-23 23:38 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +    JType_CallStaticObjectMethodPrimitiveArgAndReturn(JPy_Boolean_JClass, JPy_Boolean_ValueOf_SMID, value, objectRef);
Extra `;` (also in other places) given the macro defines it as well.

2022-09-23 23:38 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +        JType_CallStaticObjectMethodPrimitiveArgAndReturn(JPy_Long_JClass, JPy_Long_ValueOf_SMID, value.j, objectRef);
I think `jvalue value` becomes unneccessary given pattern?

2022-09-24 18:02 UTC, rbasralian commented on src/main/c/jpy_jtype.c
> +#define JType_CallStaticObjectMethodPrimitiveArgAndReturn(TARGET_TYPE, STATIC_METHOD_ID, VALUE, JOBJECT_PTR) \
renamed

2022-09-26 14:32 UTC, rbasralian commented on src/main/c/jpy_jtype.c
> +    Py_END_ALLOW_THREADS; \
Any Java allocation could theoretically lead to a lengthy GC so worth keeping that in mind

Is there any performance testing around jpy/any idea what the cost of dropping/reacquiring the GIL is?

2022-09-26 18:43 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +        JType_CREATE_JAVA_OBJECT_1_AND_RETURN(JPy_Long_JClass, JPy_Long_Init_MID, j, objectRef);
So, it's not clear to me there will be any negligible performance difference if we keep doing valueOf. In fact, these constructors are *deprecated*. Not that I think they'll ever go away, but it might be worthwhile to stick w/ valueOf.

2022-09-26 18:46 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +        JType_CREATE_JAVA_OBJECT_1_AND_RETURN(JPy_Long_JClass, JPy_Long_Init_MID, j, objectRef);
I also don't know if it makes a difference, but valueOf is HotSpotIntrinsicCandidate (I don't know if constructors are or can be?).

2022-09-26 18:59 UTC, devinrsmith commented on src/main/c/jpy_jtype.c
> +    Py_END_ALLOW_THREADS; \
It's an interesting question - are allocation points also "safepoints"? I think "yes", but the real answer may be more nuanced than that.

That said, you are probably right and the way we do it now is probably the safest option.

2022-09-26 20:31 UTC, rbasralian commented on src/main/c/jpy_jtype.c
> +        JType_CREATE_JAVA_OBJECT_1_AND_RETURN(JPy_Long_JClass, JPy_Long_Init_MID, j, objectRef);
Ok, thanks, good point. I changed it back. Doesn't make sense to use a deprecated code for performance reasons if there's no evidence it helps performance

2022-09-26 20:41 UTC, rbasralian commented on src/main/c/jpy_jtype.c
> +    JType_CallStaticObjectMethodPrimitiveArgAndReturn(JPy_Boolean_JClass, JPy_Boolean_ValueOf_SMID, value, objectRef);
I can change it, but I figured better this way because it's nice to "pretend it's a regular function" and because this is how other similar macros are used (e.g. `JPy_DELETE_LOCAL_REF`)

2022-09-27 15:25 UTC, devinrsmith approved these changes

2022-09-27 15:25 UTC, merged